#!/usr/bin/env python3
"""Train a simple action classifier from labeled candidate CSV clips."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from statistics import mean
from typing import Dict, List

import joblib
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split


FEATURE_COLUMNS = [
    "upper_body_presence",
    "torso_separation_deg",
    "left_wrist_speed",
    "right_wrist_speed",
    "mean_wrist_speed",
    "smoothed_wrist_speed",
    "hands_to_torso_distance",
    "torso_velocity",
    "hands_velocity",
    "swing_score",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a simple RandomForest action classifier from labeled CSV clips.",
    )
    parser.add_argument("--review-dir", type=Path, required=True, help="Folder generated by prepare_swing_review.py")
    parser.add_argument("--labels-json", type=Path, required=True, help="Labels exported from the HTML reviewer")
    parser.add_argument("--out-dir", type=Path, required=True, help="Where to save model artifacts")
    parser.add_argument("--test-size", type=float, default=0.25)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument(
        "--require-human-review",
        action="store_true",
        help="Train only on labels that were confirmed in review_recheck.html.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    review_dir = args.review_dir.expanduser().resolve()
    report_progress(5, "Loading labels and manifest")
    labels = json.loads(args.labels_json.read_text(encoding="utf-8"))
    manifest = json.loads((review_dir / "manifest.json").read_text(encoding="utf-8"))

    samples = []
    targets = []
    sample_meta = []
    skipped_unreviewed = 0
    skipped_missing_features = 0

    for candidate in manifest["candidates"]:
        label_info = labels.get(candidate["candidate_id"])
        if not label_info or label_info.get("label") in {None, "", "skip"}:
            continue
        if args.require_human_review and not is_human_reviewed(label_info):
            skipped_unreviewed += 1
            continue

        csv_rel_path = candidate.get("csv_rel_path")
        if not csv_rel_path:
            skipped_missing_features += 1
            continue
        csv_path = review_dir / csv_rel_path
        if not csv_path.exists():
            skipped_missing_features += 1
            continue
        rows = list(csv.DictReader(csv_path.open("r", encoding="utf-8", newline="")))
        if not rows:
            continue

        samples.append(extract_window_features(rows))
        targets.append(label_info["label"])
        sample_meta.append(
            {
                "candidate_id": candidate["candidate_id"],
                "label": label_info["label"],
                "csv_path": str(csv_path),
            }
        )

    report_progress(
        30,
        f"Collected {len(samples)} training samples; skipped {skipped_unreviewed} unreviewed labels",
    )
    if len(samples) < 4:
        raise SystemExit("Need at least 4 labeled action samples before training.")

    X = np.asarray(samples, dtype=np.float32)
    class_names = sorted(set(targets))
    class_to_index = {name: idx for idx, name in enumerate(class_names)}
    y = np.asarray([class_to_index[target] for target in targets], dtype=np.int32)

    out_dir = args.out_dir.expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    report_progress(55, "Training RandomForest classifier")
    if len(class_names) > 1 and len(samples) >= 8:
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=args.test_size,
            random_state=args.random_state,
            stratify=y,
        )
        classifier = RandomForestClassifier(
            n_estimators=200,
            max_depth=8,
            random_state=args.random_state,
        )
        classifier.fit(X_train, y_train)
        predictions = classifier.predict(X_test)
        report = classification_report(
            y_test,
            predictions,
            target_names=class_names,
            output_dict=True,
            zero_division=0,
        )
    else:
        classifier = RandomForestClassifier(
            n_estimators=200,
            max_depth=8,
            random_state=args.random_state,
        )
        classifier.fit(X, y)
        report = {"note": "Dataset too small for a meaningful holdout split; trained on all labeled samples."}

    report_progress(85, "Writing model artifacts")
    joblib.dump(
        {
            "model": classifier,
            "feature_names": make_feature_names(),
            "class_names": class_names,
            "class_to_index": class_to_index,
        },
        out_dir / "action_csv_classifier.joblib",
    )
    (out_dir / "training_report.json").write_text(
        json.dumps(
            {
                "sample_count": len(samples),
                "class_names": class_names,
                "class_to_index": class_to_index,
                "feature_names": make_feature_names(),
                "report": report,
                "samples": sample_meta,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    print(f"Model written to: {out_dir / 'action_csv_classifier.joblib'}")
    print(f"Report written to: {out_dir / 'training_report.json'}")
    if args.require_human_review:
        print(f"Skipped unreviewed labels: {skipped_unreviewed}")
    if skipped_missing_features:
        print(f"Skipped labels without CSV features: {skipped_missing_features}")
    report_progress(100, "Training complete")


def report_progress(percent: int, message: str) -> None:
    print(f"TRAIN_PROGRESS {percent} {message}", flush=True)


def is_human_reviewed(label_info: dict) -> bool:
    return bool(
        label_info.get("reviewedByHuman")
        or label_info.get("labelSource") == "human_review"
    )


def extract_window_features(rows: List[dict]) -> List[float]:
    def values(column: str) -> List[float]:
        return [float(row[column]) for row in rows]

    timestamps = values("timestamp_ms")
    duration_ms = (timestamps[-1] - timestamps[0]) if len(timestamps) > 1 else 0.0

    feature_vector = []
    for column in FEATURE_COLUMNS:
        series = values(column)
        feature_vector.extend(
            [
                float(min(series)),
                float(max(series)),
                float(mean(series)),
                float(series[-1]),
            ]
        )

    feature_vector.extend(
        [
            duration_ms,
            max(values("swing_score")),
            max(abs(value) for value in values("torso_velocity")),
            max(abs(value) for value in values("hands_velocity")),
        ]
    )
    return feature_vector


def make_feature_names() -> List[str]:
    names = []
    for column in FEATURE_COLUMNS:
        names.extend(
            [
                f"{column}_min",
                f"{column}_max",
                f"{column}_mean",
                f"{column}_last",
            ]
        )
    names.extend(
        [
            "duration_ms",
            "window_peak_swing_score",
            "window_peak_abs_torso_velocity",
            "window_peak_abs_hands_velocity",
        ]
    )
    return names


if __name__ == "__main__":
    main()
